name: Auto Post Hongkong Result

on:
  schedule:
    - cron: '0 16 * * *'  # Jam 23:00 WIB
  workflow_dispatch:

jobs:
  auto-post-hk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run HK result script
        env:
          WP_USER: ${{ secrets.WP_USER }}
          WP_PASS: ${{ secrets.WP_PASS }}
          WP_API_URL: ${{ secrets.WP_API_URL }}
        run: |
          python run.py
